version: "3"

services:
  presto:
    build:
      context: .
      dockerfile: ./example/Dockerfile
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
      - "33060"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "mainuser"
      MYSQL_PASSWORD: "mainpass"
    restart: unless-stopped
  mongodb:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: unless-stopped