version: "3.3"

services:
  presto-master:
    build:
      context: ./presto
      args:
        PRESTO_VERSION: 0.261
    ports:
      - "8080:8080"
    volumes:
      - ./presto_data/master:/var/lib/presto/data
      - ./presto/coordinator_config.properties:/opt/presto/etc/config.properties
      - ./presto/etc/catalog:/opt/presto/etc/catalog
  presto-worker:
    # build: ./presto
    build:
      context: ./presto
      args:
        PRESTO_VERSION: 0.261
    volumes:
      - ./presto/worker_config.properties:/opt/presto/etc/config.properties
      - ./presto/etc/catalog:/opt/presto/etc/catalog

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
      - "33060"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "maindb"
      MYSQL_USER: "mainuser"
      MYSQL_PASSWORD: "mainpass"
    restart: unless-stopped
  mongodb:
    image: mongo:4.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: unless-stopped
